### ISSUE TITLE
Fixed delay for first memory access

### ISSUE THREAD

**Issue by jm4rtin** [freechipsproject/rocket-chip#1147]
When running code that performs an AHB or memory access, the rocket chip seems to delay execution for a fixed amount of time.
![image](https://user-images.githubusercontent.com/20426677/33727504-7a473c94-db35-11e7-97bc-be8d5dfc28c1.png)

This happens until around a time of 0x1000:
![image](https://user-images.githubusercontent.com/20426677/33727469-59d771e0-db35-11e7-8988-32af6f13626f.png)

Do you know what is causing this?

**Comment by jm4rtin** [comment]
I'm using a tiny core configuration. If I reduce this size:
`new WithL1DCacheSets(4096)     ++ // 256kb RAM`

by half it takes until the time reads 0x800 instead (which is half the time). The memory should be a scratch but it seems like it is in some way initializing something or otherwise waiting an amount of time proportional to the size of the memory. The memory contents are not changed.

**Comment by aswaterman** [comment]
The D$ has a state machine to initialize the tag RAM, and it blocks memory accesses during that procedure.  The time is proportional to the number of lines in the cache.

**Comment by jm4rtin** [comment]
Shouldn't there be no tag cache when using a scratchpad instead of a D$? Isn't the tag_array only used in the else case for usingDataScratchpad?

**Comment by aswaterman** [comment]
Yeah, that's a performance bug we haven't bothered to fix, because it only affects reset behavior.  But since you've brought it up, I guess we should do something about it.

**Comment by jm4rtin** [comment]
I just changed flushDone:
`val flushDone = if(usingDataScratchpad) Bool(true) else (flushCounterNext >> log2Ceil(nSets)) === nWays`

Of course it's probably not optimal and may not even be right (I haven't looked into how to run the tests yet) but for now it was simple enough and my code isn't waiting for a whole lot of nothing. Reading the Chisel in the rocket can be quite challenging.

**Comment by aswaterman** [comment]
I think that's correct but not optimal.  It'll be fixed the right way later today.

**Comment by aswaterman** [comment]
Resolved by #1148
