### ISSUE TITLE
Emulator build failed 

### ISSUE THREAD

**Issue by hoangt** [freechipsproject/rocket-chip#1157]
Rocket-chip commit: a542ae68

Emulator build failed with error message 
VTestHarness.cpp:8916:138: error: ‘VL_STOP_MT’ was not declared in this scope

Changing riscv-tools to rc1.9 tag did not help. Perhaps, emulator build has not been test for recent commits

**Comment by hoangt** [comment]
Fixed by unloading existing Verilator and using Rocket's Verilator which is locally installed during emulator build.

**Comment by terpstra** [comment]
I'm glad you solved this, because I would not have guessed that was the cause!
