### ISSUE TITLE
the result of the output file

### ISSUE THREAD

**Issue by zhpzhp** [freechipsproject/rocket-chip#1169]
Hi,

The output file in the readme is like:

> C0: 483 [1] pc=[00000002138] W[r 3=000000007fff7fff][1] R[r 1=000000007fffffff] R[r 2=ffffffffffff8000] inst=[002081b3] add s1, ra, s0
> C0: 484 [1] pc=[0000000213c] W[r29=000000007fff8000][1] R[r31=ffffffff80007ffe] R[r31=0000000000000005] inst=[7fff8eb7] lui t3, 0x7fff8
> C0: 485 [0] pc=[00000002140] W[r 0=0000000000000000][0] R[r 0=0000000000000000] R[r 0=0000000000000000] inst=[00000000] unknown

But the result I got is like:

> C0:          0 [0] pc=[a57f891ff4] W[r 0=0000000000000000][0] R[r 7=0000000000000000] R[r10=87c84523a89d2fbf] inst=[a6a33b47] DASM(a6a33b47)
> C0:          1 [0] pc=[a57f891ff4] W[r 0=0000000000000000][0] R[r 7=0000000000000000] R[r10=87c84523a89d2fbf] inst=[a6a33b47] DASM(a6a33b47)
> C0:          2 [0] pc=[a57f891ff4] W[r 0=0000000000000000][0] R[r 7=0000000000000000] R[r10=87c84523a89d2fbf] inst=[a6a33b47] DASM(a6a33b47)

Is there anything I missed?

**Comment by aswaterman** [comment]
Note the "483" in the first line you qouted--that's the cycle number.  The quote in the readme is skipping the first few hundred lines of output.

**Comment by zhpzhp** [comment]
I mean the last part in each line, why I only got something like DASM(a6a33b47) but this part in the readme is assembly code?

**Comment by edcote** [comment]
@zhpzhp Try running your log through spike-dasm and report back.
