### ISSUE TITLE
Valid FP configurations (e.g. rv64imaf) cannot be created (FLEN < XLEN)

### ISSUE THREAD

**Issue by CLappin** [freechipsproject/rocket-chip#1189]
Hi,

Is it possible to generate an RV64IMAF or RV32IMAFD?

I've changed XLEN from 64 to 32, which generates an RV32IMAF core. 
I've a feeling that the answers no, as XLEN is used to determine if double precision is used or not. 
If I could get confirmation of this that would be great.

Thanks in advance for your help.

Kind Regards,
Ciaran

**Comment by aswaterman** [comment]
No, right now FLEN must equal XLEN.

**Comment by CLappin** [comment]
Perfect, thanks for clearing that up for me Andrew.

**Comment by CLappin** [comment]
Hi Andrew,

I've reopened and renamed the issue for tracking purposes. 

Thanks, 
Ciaran

**Comment by hcook** [comment]
Actually apparently #1245 gets you both!
