### ISSUE TITLE
BootROM does not use ROMGenerator, why?

### ISSUE THREAD

**Issue by edcote** [freechipsproject/rocket-chip#1231]
@terpstra

The subject of the issue should be self-explanatory.  Is there a reason why ROMGenerator is not used by BootROM.scala?

https://github.com/freechipsproject/rocket-chip/blob/e315a7aaa756d2da3b9d97ded318bb36691c5ea8/src/main/scala/devices/tilelink/BootROM.scala#L45

https://github.com/freechipsproject/rocket-chip/blob/e315a7aaa756d2da3b9d97ded318bb36691c5ea8/src/main/scala/devices/tilelink/MaskROM.scala#L40

**Comment by kammoh** [comment]
So what is the reason? Is there any way to use a MaskROM for the BootROM?
