### ISSUE TITLE
Can the data transmit from L2 to core without the dcache?

### ISSUE THREAD

**Issue by Xuwmzzz** [freechipsproject/rocket-chip#1257]
Dear all,

I found that the data be transmitted from L2 through the dcache to core.
How about transmitting from L2 to core without the dcache? 
If possible, how can i configure the rocket-chip by the scala code.

Thank you!

**Comment by terpstra** [comment]
I do not understand this question. There is no L2 in rocket-chip. Furthermore, even if there were, it would only deliver data to the core's L1D, never directly to the core.

**Comment by Xuwmzzz** [comment]
I mean that can the core extract data directly from external memory/L2? Not from the L1D.

**Comment by Xuwmzzz** [comment]
Or can I modify the value of some registers to achieve this effect?

**Comment by terpstra** [comment]
Do you mean MMIO?

**Comment by Xuwmzzz** [comment]
No, i mean that can the Dcache be used selectively when the program is running?
