### ISSUE TITLE
Little confusion about current design of instrustion fetch

### ISSUE THREAD

**Issue by Tong-Lin** [freechipsproject/rocket-chip#1278]
In current design, frontend would always replay to require data from I$ while I$ was missing; Tag and inst ram in I$ were toggled before start refilling; I think it's not a lowpower friendly behaviour; Is there any parameter that I can config to avoid this behaviour of I$;

**Comment by aswaterman** [comment]
If you're spending a large fraction of the time stalled on I$ misses, you've got bigger energy-efficiency problems than this one.

The current design supports hit-under-miss, which helps when a branch misprediction causes a wrong-path I$ miss.  If you don't need that feature, you should be able to hack the RTL to disable I$ access during miss.  (But you are on your own.)
