### ISSUE TITLE
make project failed in fpga-zynq/README.md  3.1) Project Setup 

### ISSUE THREAD

**Issue by clx7913** [freechipsproject/rocket-chip#1298]
I followed the 3.1) Project Setup of the README.md.
After typing "make project" in the directory of /fpga-zynq/zedboard,I encountered one error.
The log information is here:

root@vm:/home/chang/fpga-zynq/zedboard# make project
make -C /home/chang/fpga-zynq/rocket-chip/firrtl SBT="java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /home/chang/fpga-zynq/rocket-chip/sbt-launch.jar" root_dir=/home/chang/fpga-zynq/rocket-chip/firrtl build-scala
make[1]: Entering directory `/home/chang/fpga-zynq/rocket-chip/firrtl'
java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /home/chang/fpga-zynq/rocket-chip/sbt-launch.jar "assembly"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Getting org.scala-sbt sbt 0.13.12 ...

:: problems summary ::
:::: WARNINGS
module not found: org.scala-sbt#sbt;0.13.12

==== local: tried

  /root/.ivy2/local/org.scala-sbt/sbt/0.13.12/ivys/ivy.xml

  -- artifact org.scala-sbt#sbt;0.13.12!sbt.jar:

  /root/.ivy2/local/org.scala-sbt/sbt/0.13.12/jars/sbt.jar

==== Maven Central: tried

  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.12/sbt-0.13.12.pom

  -- artifact org.scala-sbt#sbt;0.13.12!sbt.jar:

  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.12/sbt-0.13.12.jar

==== typesafe-ivy-releases: tried

  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.12/ivys/ivy.xml

==== sbt-ivy-snapshots: tried

  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.12/ivys/ivy.xml

	::::::::::::::::::::::::::::::::::::::::::::::

	::          UNRESOLVED DEPENDENCIES         ::

	::::::::::::::::::::::::::::::::::::::::::::::

	:: org.scala-sbt#sbt;0.13.12: not found

	::::::::::::::::::::::::::::::::::::::::::::::

:::: ERRORS
Server access Error: Connection refused (Connection refused) url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.12/ivys/ivy.xml

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.13.12: not found
Error during sbt execution: Error retrieving required libraries
(see /root/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.12
make[1]: *** [/home/chang/fpga-zynq/rocket-chip/firrtl/utils/bin/firrtl.jar] Error 1
make[1]: Leaving directory `/home/chang/fpga-zynq/rocket-chip/firrtl'
make: *** [/home/chang/fpga-zynq/rocket-chip/firrtl/utils/bin/firrtl.jar] Error 2
root@vm:/home/chang/fpga-zynq/zedboard#

Anyone knows what's wrong with it ?

**Comment by clx7913** [comment]
Following the  chisel3 "Installation"  instruction,I have already installed the sbt.

But the installed version was 1.1.1.

**Comment by davidbiancolin** [comment]
Will follow up in fpga-zynq.
