### ISSUE TITLE
"A" Standard Extension (atomic memory operation) on single core and 1 Hart config

### ISSUE THREAD

**Issue by ppoocde** [freechipsproject/rocket-chip#1306]
my configuration is single core 32bit width, 1 Hart (hardware thread) processor. 
I wonder if atomic memory extension is redundant on this configuration?
my understanding is that atomic operation required multi thread operating on same memory space.
If there is only 1 core and 1 thread, "A" standard extension is irrelevant on this configuration?

**Comment by aswaterman** [comment]
Atomics are still useful in single-hart configurations for synchronization between time-multiplexed threads and for atomicity with respect to interrupts.
