### ISSUE TITLE
Remove axi interface from mem master port

### ISSUE THREAD

**Issue by ppoocde** [freechipsproject/rocket-chip#1382]
Hi everyone,
There is axi4 mem master port coming out from rocket chip. It is to interface with axi slave. My memory controller slave device are wishbone interface, instead of using axi to wishbone bridge, i m going to implement tilelink to wishbone bridge. The reason is that the axi converter from tilelink to axi take a lot of area. I wonder if anyone know how to change those axi mem master port to become tilelink interface?

Thanks

**Comment by buraktoker** [comment]
Hello,
Could you find any way to connect tilelink to wishbone interface?
Thanks
