### ISSUE TITLE
./fesvr-zynq pk hello ERROR: No cores found

### ISSUE THREAD

**Issue by clx7913** [freechipsproject/rocket-chip#1390]
Whether I used` boot.bin devicetree.dtb uImage uramdisk.image.gz` received by `make fetch-ramdisk` or used those files made by myself using `class ZynqConfig extends Config(new WithZynqAdapter ++ new DefaultFPGAConfig)` ,`./fesvr-zynq pk hello`  on zedboard always failed.

I've never encountered this kind of error.May someone help,thanks.

| ___ \ | | | | ()
| |/ / ___ | |_ __ _ | | _ _ __ _ _ __ __
| __/ / _ | _| / ` || | | || ' \ | | | |\ / /
| | | /| | | (| || |__| || | | || || | > <
_| _| _| _,|_/|||| || _,|/_/_\

PetaLinux v2013.10 (Yocto 1.4) zynq ttyPS0

zynq login: root
Password:
login[818]: root login on `ttyPS0'

root@zynq:~# ./fesvr-zynq pk hello
ERROR: No cores found

**Comment by codelec** [comment]
@clx7913 you can try this https://github.com/codelec/freedom/tree/pynq 
`make -f Makefile.debugpynq bit CONFIG=DefaultPynqConfig`
if you have any issues we can discuss it further here github.com/codelec/freedom

**Comment by clx7913** [comment]
Thank you for your reply sir.

But I only have zedboard now.

**Comment by codelec** [comment]
its the same both just have different part number and different presets. I can help you out in making the required changes

**Comment by AljawadH** [comment]
Hello! @codelec 
 I'm using Zedboard & have the same Problem (no cores found).
can you help me with it?

> its the same both just have different part number and different presets. I can help you out in making the required changes

**Comment by codelec** [comment]
i don't have solution for `no cores found` but i can help you with codelec/freedom if you run into issues

**Comment by noureddine-as** [comment]
I also had the same problem. I guess that the pre-built `fesvr-zynq` doesn't correspond to the actual source code .. in `fpga-zynq/common/src` folder. I didn't succeed to compile it. I also tried to get it back to the previous version here https://github.com/ucb-bar/fpga-zynq/issues/88 (without blockdevice support, whitch I don't understand the purpose ...).
@zhemao any ideas on that please?

Best Regards,
Noureddine.

**Comment by clx7913** [comment]
I also think it is due to the version of "fesvr-zynq". 

Unfortunately, I also couldn't rebuild the "fesvr-zynq" in "/riscv-tools/riscv-fesvr/build".

**Comment by zhemao** [comment]
Closing this as a duplicate, please follow the issue on fpga-zynq repo.

https://github.com/ucb-bar/fpga-zynq/issues/87

**Comment by heaton16** [comment]
I use the zc706. And now have this issue. Did we ever figure out what the issue was?
