### ISSUE TITLE
Is there instructions like "push" and "pop" in riscv?How to store register's value into stack?

### ISSUE THREAD

**Issue by clx7913** [freechipsproject/rocket-chip#1405]
Is there instructions like "push" and "pop" in riscv?

If I want to store some registers' values into stack,what instructions should I use?

**Comment by aswaterman** [comment]
No push/pop.  Use ```addi``` to adjust ```sp``` and then use regular loads/stores relative to ```sp```.  Here is an example function prologue:

    addi sp, sp, -16  # allocate stack frame
    sw s0, 0(sp)      # push sp
    sw ra, 4(sp)      # push ra

And an example epilogue:

    lw ra, 4(sp)      # pop ra
    lw s0, 0(sp)      # pop s0
    addi sp, sp, 16  # deallocate stack frame
    ret

**Comment by clx7913** [comment]
Thank a lot!

Detailed and helpful.
