### ISSUE TITLE
What's the actual name of "mtimecmp"?

### ISSUE THREAD

**Issue by clx7913** [freechipsproject/rocket-chip#1407]
Here is part of my own asm program:
```
	ld             t3,variable    
	csrrs	        t4,mtimecmp,t3
```
I want to access the "mtimecmp" mentioned in privileged-v1.10,which means "machine time compare register",but the building process tells me:
```
rv64mi/interrupt.S: Assembler messages:
rv64mi/interrupt.S:20: Error: Instruction csrrs requires absolute expression
```
So I doubt there is an alias instead of "mtimecmp".Any one know what's going on?

**Comment by aswaterman** [comment]
mtimecmp is memory-mapped; it’s not a CSR.

I don’t know its address offhand, but if hi look at the devicetree that gets printed when you build rocket-chip, that should give you a hint.

**Comment by clx7913** [comment]
The devicetree will be printed only on the terminal?Or it will be logged into a file?

**Comment by clx7913** [comment]
You mean this?
> [info] [0.004] Elaborating design... 
Interrupt map (2 harts 3 interrupts): 
  [1, 2] => target 
  [3, 3] => frontend 

/dts-v1/; 

/ { 
	#address-cells = <1>; 
	#size-cells = <1>; 
	compatible = "freechips,rocketchip-unknown-dev"; 
	model = "freechips,rocketchip-unknown"; 
	L13: cpus { 
		#address-cells = <1>; 
		#size-cells = <0>; 
		L5: cpu@0 { 
			clock-frequency = <0>; 
			compatible = "sifive,rocket0", "riscv"; 
			d-cache-block-size = <64>; 
			d-cache-sets = <64>; 
			d-cache-size = <16384>; 
			d-tlb-sets = <1>; 
			d-tlb-size = <32>; 
			device_type = "cpu"; 
			i-cache-block-size = <64>; 
			i-cache-sets = <64>; 
			i-cache-size = <16384>; 
			i-tlb-sets = <1>; 
			i-tlb-size = <32>; 
			mmu-type = "riscv,sv39"; 
			next-level-cache = <&L6>; 
			reg = <0>; 
			riscv,isa = "rv64imafdc"; 
			status = "okay"; 
			timebase-frequency = <1000000>; 
			tlb-split; 
			L3: interrupt-controller { 
				#interrupt-cells = <1>; 
				compatible = "riscv,cpu-intc"; 
				interrupt-controller; 
			}; 
		}; 
	}; 
	L6: memory@80000000 { 
		device_type = "memory"; 
		reg = <0x80000000 0x10000000>; 
	}; 
	L12: soc { 
		#address-cells = <1>; 
		#size-cells = <1>; 
		compatible = "freechips,rocketchip-unknown-soc", "simple-bus"; 
		ranges; 
		L10: blkdev-controller@10015000 { 
			compatible = "ucbbar,blkdev"; 
			interrupt-parent = <&L0>; 
			interrupts = <3>; 
			reg = <0x10015000 0x1000>; 
			reg-names = "control"; 
		}; 
		L1: clint@2000000 { 
			compatible = "riscv,clint0"; 
			interrupts-extended = <&L3 3 &L3 7>; 
			reg = <0x2000000 0x10000>; 
			reg-names = "control"; 
		}; 
		L2: debug-controller@0 { 
			compatible = "sifive,debug-013", "riscv,debug-013"; 
			interrupts-extended = <&L3 65535>; 
			reg = <0x0 0x1000>; 
			reg-names = "control"; 
		}; 
		L7: error-device@3000 { 
			compatible = "sifive,error0"; 
			reg = <0x3000 0x1000>; 
			reg-names = "mem"; 
		}; 
		L9: external-interrupts { 
			interrupt-parent = <&L0>; 
			interrupts = <1 2>; 
		}; 
		L0: interrupt-controller@c000000 { 
			#interrupt-cells = <1>; 
			compatible = "riscv,plic0"; 
			interrupt-controller; 
			interrupts-extended = <&L3 11 &L3 9>; 
			reg = <0xc000000 0x4000000>; 
			reg-names = "control"; 
			riscv,max-priority = <7>; 
			riscv,ndev = <3>; 
		}; 
		L8: rom@10000 { 
			compatible = "sifive,rom0"; 
			reg = <0x10000 0x10000>; 
			reg-names = "mem"; 
		}; 
	}; 
}; 

Generated Address Map 
	       0 -     1000 ARWX  debug-controller@0 
	    3000 -     4000 ARWX  error-device@3000 
	   10000 -    20000  R XC rom@10000 
	 2000000 -  2010000 ARW   clint@2000000 
	 c000000 - 10000000 ARW   interrupt-controller@c000000 
	10015000 - 10016000 ARW   blkdev-controller@10015000 
	80000000 - 90000000  RWXC memory@80000000

**Comment by clx7913** [comment]
I find some .json files in emulator,and I think that's what you mention.

**Comment by clx7913** [comment]
```
...
{
      "mtimecmp_0_0" : {
        "byteOffset" : "0x4000",
        "bitOffset" : 0,
        "bitWidth" : 8,
        "name" : "mtimecmp_0_0",
        "group" : "mtimecmp_0",
        "groupDesc" : "MTIMECMP for hart 0",
        "accessType" : "RW"
      }
    }, {
      "mtimecmp_0_1" : {
        "byteOffset" : "0x4000",
        "bitOffset" : 8,
        "bitWidth" : 8,
        "name" : "mtimecmp_0_1",
        "group" : "mtimecmp_0",
        "accessType" : "RW"
      }
    }, {
      "mtimecmp_0_2" : {
        "byteOffset" : "0x4000",
        "bitOffset" : 16,
        "bitWidth" : 8,
        "name" : "mtimecmp_0_2",
        "group" : "mtimecmp_0",
        "accessType" : "RW"
      }
    }, {
      "mtimecmp_0_3" : {
        "byteOffset" : "0x4000",
        "bitOffset" : 24,
        "bitWidth" : 8,
        "name" : "mtimecmp_0_3",
        "group" : "mtimecmp_0",
        "accessType" : "RW"
      }
    }, {
      "mtimecmp_0_4" : {
        "byteOffset" : "0x4000",
        "bitOffset" : 32,
        "bitWidth" : 8,
        "name" : "mtimecmp_0_4",
        "group" : "mtimecmp_0",
        "accessType" : "RW"
      }
    }, {
      "mtimecmp_0_5" : {
...
```

**Comment by clx7913** [comment]
Now I know what to do,thanks!
