### ISSUE TITLE
Error during elaborate phase (different than previous post)

### ISSUE THREAD

**Issue by Onamix** [freechipsproject/rocket-chip#1455]
hi there.

i am trying to build the default rocket-chip. nothing fancy.

when i go into vsim and type "make" i get the following error:

```
[info] [0.003] Elaborating design...
Interrupt map (2 harts 2 interrupts):
  [1, 2] => dut

[error] (Thread-13) java.io.IOException: Cannot run program "dtc": error=2, No such file or directory
[error] java.io.IOException: Cannot run program "dtc": error=2, No such file or directory
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
[error]         at scala.sys.process.ProcessImpl$PipedProcesses.runAndExitValue(ProcessImpl.scala:132)
[error]         at scala.sys.process.ProcessImpl$CompoundProcess$$anonfun$1.apply$mcV$sp(ProcessImpl.scala:94)
[error]         at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:23)
[error] Caused by: java.io.IOException: error=2, No such file or directory
```

the stacktrace (not sure if this is the right word) is going on for quite some time. if you need the rest i will post it.

i have no idea how to use scala or java and found no solution by searching the internet. apperently scala is using the java virtual machine and i have the version 8 from oracle.

thank you very much in advance!

**Comment by mayoru** [comment]
Have you installed device-tree-compiler and all other dependencies?
See https://github.com/riscv/riscv-tools/blob/priv-1.10/README.md#quickstart
