### ISSUE TITLE
Is there UART module in Rocket-chip?

### ISSUE THREAD

**Issue by clx7913** [freechipsproject/rocket-chip#1498]
If I implement the Rocket-chip on Zedboard, is there UART of Rocket-chip in the PL part of Zedboard?

**Comment by morse-michael** [comment]
SiFive have implemented a UART in Scala, see https://github.com/sifive/sifive-blocks/tree/c340d7ade16a9bea307685c54a13d830fa90bc3b/src/main/scala/devices/uart

See https://github.com/sifive/freedom for a RISC-V FPGA platform which includes Rocket + UART, mapping that on Zedboard shouldn't be too difficult.

**Comment by clx7913** [comment]
Great! I'll study it.
