### ISSUE TITLE
Assert in the SimpleHellaCacheIF module 

### ISSUE THREAD

**Issue by aicr** [freechipsproject/rocket-chip#1512]
I trying to use the data memory interface between the RoCC and the D-mem/D-cache.
Upon testing it,  I got the assertion defined in SimpleHellaCacheIF.scala triggered.
```
    assert(!RegNext(RegNext(io.cache.req.fire())) || !io.cache.s2_xcpt.asUInt.orR,
         "SimpleHellaCacheIF exception")   
```
Can someone explain why am I getting the assertion triggered ? any pointers ?
The exception signal that the cache issues is "**io_cache_s2_xcpt_ma_ld**", what does it mean ?

**Comment by aswaterman** [comment]
It's not legal for RoCCs to send requests to the D$ that cause exceptions.  Need to check for address validity first.

**Comment by aicr** [comment]
Hi, @aswaterman  can you elaborate more on the address validity check ?
After digging a little bit in the code , I now understand (or I think i do) that this is misaligned load address.
However, my address is 0x80003FDC which word (4 bytes) aligned and my d-cache is at at  address 0x80000000 and size 16kb

**Comment by aswaterman** [comment]
And the 'typ' field you're sending the data cache is set to 2 (i.e. 4 bytes)?

**Comment by aswaterman** [comment]
Glad to be of help (although this is about the limit of my RoCC knowledge!)
