### ISSUE TITLE
RoccExampleConfig throwing java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by seldridge** [freechipsproject/rocket-chip#1515]
On master with `RoccExampleConfig` I'm getting a `java.lang.IllegalAccessError` tied to [line 91 of LazyRoCC.scala](https://github.com/freechipsproject/rocket-chip/blob/master/src/main/scala/tile/LazyRoCC.scala#L91) which doesn't seem to make sense. This seems to be trying to access some reflection-related member in `RocketTileModuleImp` from `LazyRoCC` and failing, but I'm having some trouble understanding exactly what is going on here.

```
[error] Caused by: java.lang.IllegalAccessError: tried to access field freechips.rocketchip.tile.RocketTileModuleImp.reflPoly$Cache4 from class freechips.rocketchip.tile.HasLazyRoCCModule$class
[error] 	at freechips.rocketchip.tile.HasLazyRoCCModule$class.reflMethod$Method4(LazyRoCC.scala:91)
```

To reproduce this:

```bash
make CONFIG=RoccExampleConfig
```

Somewhat strangely, some initial triage of this where I commented out line 91, built, uncommented, and then built resulted in this switching to a `NullPointerException` tied to [line 105](https://github.com/freechipsproject/rocket-chip/blob/master/src/main/scala/tile/LazyRoCC.scala#L105). (A stateful error? :fearful:)

h/t @aroelke

**Comment by colinschmidt** [comment]
Does this present on a clean repo? Sometimes strange stateful errors crop up with bad sbt caching (i.e. try deleting target et al)

**Comment by seldridge** [comment]
Good question... I tested this on a clean clone and got this behavior. For some added sanity on the environment, I blew away my local `~/.ivy2` just in case that was contributing.

A full stack trace is available here: https://gist.github.com/seldridge/b5ebcd2e3a0357a93ccd83a7df3f4289

**Comment by seldridge** [comment]
After bisecting to check if Rocket gets past elaboration, c563c9ce83af70dfbd019aa1701d71b4ac60e700 appears to be the breaking commit.

**Comment by aswaterman** [comment]
It's not obvious to me why that broke it.  LMK if you figure it out...

**Comment by seldridge** [comment]
@aswaterman: I'm glad I'm not the only one!

I'm still lost on the specific reflection error. Sometimes this chooses to manifest as a complaint about `fpuOpt` being `null` (which it is when the `HasLazyRoCCModule` constructor is running). I can get around this with a `roccInit` method or something, but that leads back to the reflection error.

I'll pull on it and see where I get.

I will also (finally) push a PR to just build `RoccExampleConfig` in Travis once this error is corrected.
