### ISSUE TITLE
How to flush and invalidate cache lines in Rocket?

### ISSUE THREAD

**Issue by clx7913** [freechipsproject/rocket-chip#1524]
Is it possible to implement these two operations by assembler or C code? Or do I need to add extra hardware?

**Comment by hcook** [comment]
Not currently supported.

The Core<=>DCache interface has [memory opcodes](https://github.com/freechipsproject/rocket-chip/blob/master/src/main/scala/rocket/Consts.scala#L83) provisioned to describe a few cache control operations, but the Rocket core doesn't issue them and the dcaches don't yet obey them.

The SW-managed cache control extension to RISC-V has not yet even reached the formal proposal stage.

**Comment by clx7913** [comment]
OK, thank you for your instruction.
