### ISSUE TITLE
Memory map questions

### ISSUE THREAD

**Issue by juliusbaxter** [freechipsproject/rocket-chip#1579]
I'm stuck in a situation where I have a non-power-of-two-sized peripheral and want to get the true size of this peripheral in the $DESIGN.memmap.json file the Rocket chip generator kicks out. I parse that memmap.json file to generate some C headers, but the size of the peripheral's address space is is not being presented in a plain form.

The AddressSet() guy seems to take a base address and mask corresponding to the size of region the peripheral covers. It is clever when it detects a non-power-of-two sized mask and breaks it up into as many power-of-two regions as necessary. That's great, but at some point I still just want to have the full size of my peripheral come out in a JSON file somewhere.

How do I get that?

An additional query I have is whether there is a way to get arbitrary information from my block into the generated memory map? That $DESIGN.memmap.json, as far as I can tell, is some arbitrary format, in that it's not some DTS-related format, is it?

What would be awesome is to be able to pass through as much parameterisation information as I like to the JSON files the flow generates.

**Comment by terpstra** [comment]
There is an AddressRange.fromSets function which can convert a sequence of AddressSets into contiguous regions. AFAIK, this is already used when creating DTS output, so your device should already be expressed with it's true size and offset. Can you post the offending addresses?

**Comment by terpstra** [comment]
You can already include additional information about your device into DTS. See src/main/scala/devices/tilelink/Plic.scala:69. The describe override adds fields to the PLIC dts output.

**Comment by juliusbaxter** [comment]
Thanks for the pointer on the DTS. Perhaps I'll start parsing that instead of the memmap.json. Although it doesn't seem to be a format easily parsable by Python (it's almost YAML but not quite).

I want to define a region starting at 1MB which is 768kB in size. This size may change as well, so what I want to do is rely on something from the flow which I can use in my C which describes how big this region is.

What ends up getting passed to the TLManagerParameters's address parameter is List(AddressSet(0x100000,(768*1024)-1))

That is probably incorrect, because I get this in my DTS:

```
L25: mem_bridge@100000 {
			reg = <0x100000 0x40000 0x180000 0x40000>;
		};
```
Which is a 256kB region at 1MB, and then another 256kB region at 1.5MB, skipping the middle third 256kB.

So that's just wrong, but I guess it's because 768*1024-1 = 0xBFFFF, where there's a 0 in the 18th bit, 1<<18 is 0x40000 which I guess corresponds to the region from 0x40000-0x80000 which the above DTS snippet misses out.

However, what is really behind this region is a memory bank comprised of multiple 64kB RAM instances, and actually it might be useful to specify each of those individually and have my DTS/memmap.json processing script tally up the memory regions itself.

Although, when I do it this way:
```
     addresses = List(
       // 12 x 64kB instances
       AddressSet(0x100000,0xFFFF),
       AddressSet(0x110000,0xFFFF),
       AddressSet(0x120000,0xFFFF),
       AddressSet(0x130000,0xFFFF),
       AddressSet(0x140000,0xFFFF),
       AddressSet(0x150000,0xFFFF),
       AddressSet(0x160000,0xFFFF),
       AddressSet(0x170000,0xFFFF),
       AddressSet(0x180000,0xFFFF),
       AddressSet(0x190000,0xFFFF),
       AddressSet(0x1A0000,0xFFFF),
       AddressSet(0x1B0000,0xFFFF)
```

I get the correct size in the DTS and memory map, but only a single region?! I would've thought passing multiple explicit address sets would generate multiple regions.

Anyway, that's the way to get what I need I think. I can encode the memory topology another way I suppose.

**Comment by juliusbaxter** [comment]
And thanks again for the pointer to the example of overriding the describe function in a SimpleDevice (src/main/scala/devices/tilelink/Plic.scala:69) it did exactly what I wanted.

Will close this, I more or less got what I wanted.

**Comment by terpstra** [comment]
AddressSet(0x100000, 0xBFFFF) matches addresses where (address & ~ 0xBFFFF) == 0x100000.

So that is not a contiguous range as you've discovered. You can use AddressSet.misaligned(0x100000, 0xC0000) to create a sequence of AddressSets that cover the whole range.

The DTS merges address range fragments automatically, so your manual fracturing into 64kB addresses will make no difference.

**Comment by jerryhethatday** [comment]
> AddressSet(0x100000, 0xBFFFF) matches addresses where (address & ~ 0xBFFFF) == 0x100000.
> 
> So that is not a contiguous range as you've discovered. You can use AddressSet.misaligned(0x100000, 0xC0000) to create a sequence of AddressSets that cover the whole range.
> 
> The DTS merges address range fragments automatically, so your manual fracturing into 64kB addresses will make no difference.

I wonder why you guys design the AddressSet? I feel like it is very diffcult to understand the design consideration of this, I know you want to represent an address range using this, but why not just using the form (baseaddr, offset)? Thanks, it halts me for a long while.
