### ISSUE TITLE
Can rocket be configured to a E31/E21 like core?

### ISSUE THREAD

**Issue by zhouqinghua** [freechipsproject/rocket-chip#1620]
Hi, I want to know if rocket-chip can be configured to E31/E21(SiFive) core or similar ones?
Seems, only change config file is not enough. Is it possible to finish this with limited modifications to the chisel code?

thanks a lot.

**Comment by Mixermachine** [comment]
What version of rocket-chip do you have checked out?
When you have a look at the freedom repo (SiFive repo) here **https://github.com/sifive/freedom** you can see that they reference a older version of the rocket-chip repo and add some other components to the project.

Greetings from Munich :)
