### ISSUE TITLE
what's the purpose of ccover?

### ISSUE THREAD

**Issue by janboeye** [freechipsproject/rocket-chip#1627]
hi, 

There is ccover invoked in Icache, dcache, TLB and PTW.  I do not understand what's the mean of ccover and what's the purpose?

Thanks

**Comment by janboeye** [comment]
The final return is unit and actually does nothing. Why adds cover in icache, dcache and tilelink?

@aswaterman 

Thanks

**Comment by jackkoenig** [comment]
A tiny amount of context is provided here: https://github.com/freechipsproject/rocket-chip/blob/3e2c304a782ef9a0d06b8cfab4c78f49f9fc1674/src/main/scala/util/Property.scala#L132

The idea is that they serve as hooks for a coverage library implementation. You could provide your own if you wish to use them as coverage. We were hoping a good library would be available by now; if you or anyone would like to work on this I can provide some ideas on how to go about it
