### ISSUE TITLE
Source code refactoring

### ISSUE THREAD

**Issue by tampler** [freechipsproject/rocket-chip#1814]
I created a fork from this project with a goal to update its build flow and refactor Chisel sources.
[Here's my project](https://github.com/Neurodyne/rocketchip_refactored).

I added Scapegoat linting and Coverage reports and moved to the latest versions of FIRRTL and Chisel3.
I get lots of issues on compile. Is anybody interested in working on that with me ?

You may get a report with make lint in the project root

I also opened an issue in [RFC](https://github.com/freechipsproject/rfcs/issues/4).

**Comment by dhanna11** [comment]
On a related note, I started adding Bazel build rules to Rocket chip and it's dependencies.
A very rough WIP can be found here. https://github.com/dhanna11/rules_rocketchip_meta
Requires bazel 0.16
