### ISSUE TITLE
Question about the cache on emulator

### ISSUE THREAD

**Issue by chriszhang75** [freechipsproject/rocket-chip#598]
I have compiled the emulator with DeaultRV32Config. I want to make the delay of core to get the instruction and data is zero.  
   My question is :
             1) Is there a config file for emulator without cache?
             2) If there is always a L1 cache on the emulator, One way I tried is to increase the size of L1 cache that all the instructions can be stored. are there some methods i can take to confirm that the delay of core to get the instruction and data is zero？

**Comment by terpstra** [comment]
Rocket must always run from an I-cache. If you don't want to use the D-cache, the easiest thing to do is restrict the loads/stores in your program to the MMIO region.
