### ISSUE TITLE
Fsim directory and other directories in the slides

### ISSUE THREAD

**Issue by ninode** [freechipsproject/rocket-chip#661]
Hello, 
This might be a silly question. And for that I apologize.
In Colin Schmidt's Rocket-chip tutorial. There are directories that I don't find in the rocket-chip git such as fsim, fpga-zynq, Uncore etc...) I'm wondering if there have been new modifcations regarding the folders or should I just install the missing ones. 

Thank you

**Comment by colinschmidt** [comment]
There have been a lot of modifications since then. The fpga stuff has been moved out of rocket-chip and lives in ucb-bar/fpga-zynq most of the other folders moved from being git submodules to folders in src/main/scala/

**Comment by ninode** [comment]
Thank you for your response. 
So would the old tutorial still apply if I build things accordingly ? Have you made any recent tutorial slides ?

Thank you
