### ISSUE TITLE
S vs U in ISA string?

### ISSUE THREAD

**Issue by sorear** [freechipsproject/rocket-chip#664]
I built rocket-chip and got this in the dts file:

```
riscv,isa = "rv64imafdcs";
```

1. User spec §11.6 says that S is a prefix character which is followed by a one-letter code identifying an extension that is only applicable in S-mode.  By implication a bare "s" at the end of the string does not have a defined meaning.

2. Privileged spec `misa` uses `S` for S-mode support and `U` for U-mode support.  If the ISA string is intended to follow that, then would it also contain a `u`?

**Comment by terpstra** [comment]
@aswaterman What to do? I recall at some point you said to not include an 's' at all. Is that still the plan? Note we already have "mmu-type = sv39" so it is redundant.

**Comment by terpstra** [comment]
Spike says riscv,isa = "rv64imafdc", so it looks like maybe we should just make rocket-chip do the same thing?

**Comment by aswaterman** [comment]
S-mode implies U-mode, so putting 's' in the string but not 'u' is OK, I think.  Maybe the string should be ```rv64imafdcs_sv39```?  I'll also see what @kasanovic thinks.

Regardless, Spike and Rocket should agree.

**Comment by terpstra** [comment]
I'd leave the sv39 part off and put it in the (standard) mmu-type field where it already is.

**Comment by aswaterman** [comment]
I wrote that because of what the user ISA spec says in Sec. 11.6: "Standard supervisor instruction subsets are defined in Volume II, but are named using “S” as a prefix, followed by a supervisor subset name beginning with a letter and an optional version number."

I can't remember whether we intended Sv39 to fit that definition.

**Comment by terpstra** [comment]
This was fixed in #740
