### ISSUE TITLE
How to know how many cycles the program takes on emulator?

### ISSUE THREAD

**Issue by ViccoYang** [freechipsproject/rocket-chip#677]
I can run my own test case on emulator now, but how can I know how many cycles the test case takes?
The benchmarks and assembly tests give .out files but it seems to be a total cycles cost, can we get more detailed? For example a qsort test may contain different functions, can we know the number of cycles  each function takes?
Thanks for your help!

**Comment by terpstra** [comment]
There is no provision for doing this in rocket. I suppose you could post-process the +verbose output, looking at the retired instruction PCs.
