### ISSUE TITLE
Assertion `n <= ram_words()' failed in master branch emulator run

### ISSUE THREAD

**Issue by edisontime** [freechipsproject/rocket-chip#730]
Hi;
in master branch, i followed instructions in readme.md, after build toolchain,
then in the emulator dir, 
when i "make run", then it fails in any test.

in each *.out file like:
$ cat output/rv64um-v-mul.out
emulator-rocketchip-DefaultConfig: ../fesvr/dtm.cc:69: uint32_t dtm_t::run_program(const uint32_t*, size_t, size_t): Assertion `n <= ram_words()' failed.

do you konw how can i fix this?
or is the master branch not stable, need i switch to a different branch?
and wher i can get each branch's meaning, is there any discription?

Thank you verymuch!
(I've tried boom branch, and it's emulator runs ok, but there's still boom-devel branch... so i am confused..)

**Comment by mwachs5** [comment]
Are you sure you were using the right version of riscv-tools/riscv-fesvr? This sounds like a mismatch.
