### ISSUE TITLE
VCS doesn't compile when TLMonitorBuilder is set to None

### ISSUE THREAD

**Issue by aswaterman** [freechipsproject/rocket-chip#764]
...presumably because there are no instantiations of plusarg_reader, causing VCS to instantiate one as a top-level module.  I'm currently working around this by changing the "borked" string to "%d".

    Error-[STASKE_VPAMHFS] Invalid argument to $value$plusargs
    /scratch/waterman/federation/rocket-chip/vsrc/plusarg_reader.v, 17
      An invalid plusarg_format string 'borked' is passed as first argument to
      $value$plusargs.
      Please ensure that the first argument to $value$plusargs is a valid
      plusarg_format specifier string.

**Comment by aswaterman** [comment]
If you don't object, I can commit my workaround.

**Comment by terpstra** [comment]
Lol. That's a funny bug. Your fix seems fine to me.

**Comment by terpstra** [comment]
Actually, use "borked=%d"

**Comment by aswaterman** [comment]
ok :)
