### ISSUE TITLE
How to customize the number of tiles/cores ? 

### ISSUE THREAD

**Issue by yargo11** [freechipsproject/rocket-chip#795]
I want to increase the number of cores/tiles in my project. So, what i need to do, and how i can check/confirm it`s working?

I change the parameter NTILES for 4(fpga-zynq/rocket-chip/src/main/scala/uncore/builder.scala) and after this i executed the command $ make fpga-images-zezboard/boot.bin on zedboard directory.

Copy the files inside /fpga-zynq/zedboard/ for SD, insert SD on the Zedboard and turn on the board.
When i execute "grep -c ^processor /proc/cpuinfo", i got 2 as response for the command.
If a execute ./fesvr-zynq bbl and try execute "grep -c ^processor /proc/cpuinfo" again, i got 0 as response.

**Comment by ben-k** [comment]
Please don't open the same issue across multiple projects - I've responded to the other instance of this (ucb-bar/fpga-zynq/issues/47).
