### ISSUE TITLE
RegisterReadIO and RegisterWriteIO need cloneType method

### ISSUE THREAD

**Issue by zhemao** [freechipsproject/rocket-chip#817]
The regmapper interface is pretty slick, but one hangup is that RegisterReadIO and RegisterWriteIO don't have cloneType methods. That means you can't wrap them in a Wire, which would be very useful if you just want to connect existing decoupled interfaces to request and response. Right now, I work around it using the function-based constructor, but it would be more convenient to just declare a wire.

**Comment by zhemao** [comment]
@terpstra could you take a look at this? I can submit a pull request if need be, but the change required should be pretty straightforward.

**Comment by terpstra** [comment]
RefReadFn and RegWriteFn already accept a ReadyValidIO, from which DecoupledIO is derived. That said, if you want to add a cloneType, I'd merge it.

**Comment by zhemao** [comment]
Yes, but using a ReadyValidIO is semantically different from using a RegisterReadIO. It doesn't allow you to decoupled the read request from the read response. I've submitted a PR.
