### ISSUE TITLE
Make it so we don't need to do the travis hackery ever again

### ISSUE THREAD

**Issue by mwachs5** [freechipsproject/rocket-chip#831]
branches:
  only:
    - "master"

Apparently we can add that to our travis.yml and then we dont need to keep switching the "build branch updates" toggle:

(from this thread: https://github.com/travis-ci/travis-ci/issues/1147)

**Comment by terpstra** [comment]
You would still end up having to run travis twice for every PR. Once in push and once on merge. Given the limited build power, I'm not sure this is a good plan.

**Comment by mwachs5** [comment]
You could always kill the merge job... Now that you are allowing merge commits which are true merges, I don't think that's really a bad idea.

**Comment by terpstra** [comment]
If we had infinite build jobs, I would totally be in favour of this PR. I suppose it won't bother anyone with Travis admin privileges, because they can cancel it, as you suggest. I dunno. I abstain from reviewing this PR. Let's see what @aswaterman and @hcook think.

**Comment by mwachs5** [comment]
Yeah. I think the other right fix is to find a way to make the riscv-tools bump less painful. Anyway I don't feel too strongly about it, just googling while waiting for runs to pass :)
