### ISSUE TITLE
UIntToOH1 in PMP.scala

### ISSUE THREAD

**Issue by pentin-as** [freechipsproject/rocket-chip#920]
54:
      val lsbMask = mask | ~(((BigInt(1) << lgMaxSize) - 1).U << lgSize)
      val lsbMask = mask | UIntToOH1(lgSize, lgMaxSize)
74:
    !boundMatch(x, ~(((BigInt(1) << lgMaxSize) - 1).U << lgSize)(lgMaxSize-1, 0), lgMaxSize)
    !boundMatch(x, UIntToOH1(lgSize, lgMaxSize), lgMaxSize)
108:
    val lsbMask = ~(((BigInt(1) << lgMaxSize) - 1).U << lgSize)(lgMaxSize-1, 0)
    val lsbMask = UIntToOH1(lgSize, lgMaxSize)

**Comment by terpstra** [comment]
What seems to be the problem?

**Comment by aswaterman** [comment]
I believe this is a suggestion to write UIntToOH1 instead of (1 << x) - 1.

**Comment by terpstra** [comment]
I see. That's a good idea since UIntToOH does not require an adder of any kind after the barrel shifter.

**Comment by terpstra** [comment]
Right. Your existing circuit is essentially the same, but I guess a bit less clear.

**Comment by aswaterman** [comment]
DC actually picks up the (1<<x)-1 pattern, but the code is cleaner with the change.
