### ISSUE TITLE
Error with Vsim "make"

### ISSUE THREAD

**Issue by riscveval** [freechipsproject/rocket-chip#949]
Hi,

after updating to the newest rocket-chip I got this error while trying to build the VCS Simulator. In a clean checkout, I did the following to produce the error:

cd vsim
make 

cc1: warning: command line option '-std=c++11' is valid for C++/ObjC++ but not for C
SimDTM.o: In function `debug_tick':
SimDTM.cc:(.text+0x254): undefined reference to `dtm_t::dtm_t(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/nfs/iind/disks/i2r.disk.0001/RISCV_Evaluation/Free-chip_project/riscv/lib/libfesvr.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make[1]: *** [product_timestamp] Error 1

Thanks,

**Comment by aswaterman** [comment]
This is a system issue outside the scope of what we can support here.

I noticed you're using a shared file system.  The linking issue you referenced might show up if you built libfesvr on system X but built the simulator on system Y.
