### ISSUE TITLE
Support for underscores in diplomacy.AddressSet

### ISSUE THREAD

**Issue by hcook** [freechipsproject/rocket-chip#962]
Scala does not natively support underscores in numeric literals, but it is fairly straightforward to add via an implicit class:
https://stackoverflow.com/questions/31275887/underscores-in-numeric-literals-in-scala

Since Diplomacy is dependent on AddressSets/BigInts to create the address map, would it be reasonable to add support for StringContext=>IntContext to the library?

**Comment by terpstra** [comment]
I agree it's easy to get lost in the number of 0s. Have I understood correctly you want something like: AddressSet(hex"20_0000_0000", hex"ffff_ffff") ?
