### ISSUE TITLE
Open GPU architecture

### ISSUE THREAD

**Issue by vineet1323** [freechipsproject/rocket-chip#967]
First of all this is great project for Computer industries.  But, without GPU, computer is incomplete. Have any plan about also for open GPU for future. Open GPU architecture like closed GPU architecture like ARM based Mali GPU architecture.

**Comment by vineet1323** [comment]
Open GPU architecture like closed source GPU architecture Mali from ARM

**Comment by vineet1323** [comment]
Thanks

**Comment by edcote** [comment]
This issue isn't relevant to rocket-chip.

You can start by looking at http://miaowgpu.org/

I recommend you close this issue.

**Comment by vineet1323** [comment]
Ok thanx.
