### ISSUE TITLE
Plan for scala 2.12 bump?

### ISSUE THREAD

**Issue by edcote** [freechipsproject/rocket-chip#969]
Are there plans to bump scala to 2.12 or should we stay on 2.11?

My reason for 2.12: see (Inferred types for fields)[http://www.scala-lang.org/news/2.12.0/]

**Comment by aswaterman** [comment]
Soon, just need to address some minor complications: https://github.com/freechipsproject/chisel3/issues/606

**Comment by edcote** [comment]
Thanks. Following that issue now. Please close.
